version: "3.4"

services:
  database:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=godeploy
      - POSTGRES_PASSWORD=godeploy
      - POSTGRES_USER=godeploy
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  rabbitmq:
    image: rabbitmq:3.9-alpine
    restart: unless-stopped
    volumes:
      - amqp_data:/var/lib/rabbitmq
  
  server:
    image: mehdibo/godeploy:latest
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      - database
      - rabbitmq
    environment:
      #- APP_ENV=dev # Default is prod
      #- LISTEN_PORT=8080 # Default is 8080
      - DB_HOST=database
      - DB_USER=godeploy
      - DB_PASS=godeploy
      - DB_NAME=godeploy
      #- DB_PORT=5432 # Default is 5432
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASS=guest
      #- AMQP_PORT=5672 # Default is 5672
    
  consumer:
    image: mehdibo/godeploy:latest
    restart: unless-stopped
    depends_on:
      - database
      - rabbitmq
    environment:
      #- APP_ENV=dev # Default is prod
      - DB_HOST=database
      - DB_USER=godeploy
      - DB_PASS=godeploy
      - DB_NAME=godeploy
      #- DB_PORT=5432 # Default is 5432
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASS=guest
      #- AMQP_PORT=5672 # Default is 5672
      #- SSH_PASSPHRASE= # SSH private key passphrase if any
    volumes:
      - ./ssh_private_key:/etc/ssh_private_key:ro
    entrypoint: "/entrypoint.sh consumer"


volumes:
  db_data:
  amqp_data: